=== Jamextreme140/CodenameEngine-Develop/art/codename-engine-character.dtd
<!ELEMENT character (anim*)>
<!ATTLIST character 
    x NMTOKEN "0"
    y NMTOKEN "0"
    sprite CDATA #IMPLIED
    isPlayer (true|false) "false"
    scale NMTOKEN #IMPLIED
    camx NMTOKEN "0"
    camy NMTOKEN "0"
    flipX (true|false) "false"
    antialiasing (true|false) "true"
    gameoverChar CDATA #IMPLIED
    icon CDATA #IMPLIED
    color CDATA #IMPLIED
    holdTime NMTOKEN #IMPLIED
>

<!ELEMENT anim (#PCDATA)>
<!ATTLIST anim 
    name CDATA #REQUIRED
    anim CDATA #REQUIRED
    indices CDATA #IMPLIED
    type (beat|loop) #IMPLIED
    fps NMTOKEN "24"
    x NMTOKEN #IMPLIED
    y NMTOKEN #IMPLIED
    forces (true|false) #IMPLIED
    loop (true|false) "false"
>

=== Jamextreme140/CodenameEngine-Develop/assets/data/characters/bf.xml
<!DOCTYPE character SYSTEM "../../../art/codename-engine-character.dtd">
<character y="350" sprite="bf" flipX="true" isPlayer="true" icon="bf" color="#31B0D1">
	<anim name="idle" anim="BF idle dance" x="-5" y="0" fps="24" loop="false"/>
	<anim name="singUP" anim="BF NOTE UP0" x="-39" y="27" fps="24" loop="false"/>
	<anim name="singLEFT" anim="BF NOTE LEFT0" x="6" y="-7" fps="24" loop="false"/>
	<anim name="singRIGHT" anim="BF NOTE RIGHT0" x="-48" y="-6" fps="24" loop="false"/>
	<anim name="singDOWN" anim="BF NOTE DOWN0" x="-17" y="-50" fps="24" loop="false"/>
	<anim name="singUPmiss" anim="BF NOTE UP MISS" x="-35" y="27" fps="24" loop="false"/>
	<anim name="singLEFTmiss" anim="BF NOTE LEFT MISS" x="6" y="19" fps="24" loop="false"/>
	<anim name="singRIGHTmiss" anim="BF NOTE RIGHT MISS" x="-44" y="22" fps="24" loop="false"/>
	<anim name="singDOWNmiss" anim="BF NOTE DOWN MISS" x="-16" y="-19" fps="24" loop="false"/>
	<anim name="hey" anim="BF HEY" x="-3" y="6" fps="24" loop="false"/>
	<anim name="scared" anim="BF idle shaking" x="-6" y="1" fps="24" loop="true"/>
	<anim name="hit" anim="BF hit" x="13" y="19" fps="24" loop="false"/>
	<anim name="pre-attack" anim="bf pre attack" x="-47" y="-36" fps="24" loop="false"/>
	<anim name="attack" anim="boyfriend attack" x="289" y="270" fps="24" loop="false"/>
	<anim name="dodge" anim="boyfriend dodge" x="-8" y="-13" fps="24" loop="false"/>
</character>
